from __future__ import annotations

from pathlib import Path

import pytest
import torch

from probixi.multigpu import (
    BlockConfig,
    block_bounds,
    merge_streams,
    resolve_devices,
    run_block,
)

REPO_ROOT = Path(__file__).parent.parent
RUN_LST = REPO_ROOT / "test_data" / "run1.lst"
RUN_GEOM = REPO_ROOT / "test_data" / "Eiger4M-v1.geom"
RUN_CELL = REPO_ROOT / "test_data" / "bR.cell"


# --------------------------------------------------------------------------- #
# block_bounds
# --------------------------------------------------------------------------- #
@pytest.mark.parametrize(
    "total,world",
    [(810, 4), (10, 3), (7, 8), (100, 1), (1, 1), (0, 3), (256, 8)],
)
def test_block_bounds_covers_range_contiguously(total, world):
    bounds = [block_bounds(0, total, r, world) for r in range(world)]
    # contiguous: each block starts where the previous ended, spanning [0, total)
    assert bounds[0][0] == 0
    assert bounds[-1][1] == total
    for a, b in zip(bounds, bounds[1:]):
        assert a[1] == b[0]
    # full, non-overlapping coverage
    assert sum(hi - lo for lo, hi in bounds) == total
    # balanced: sizes differ by at most one
    sizes = [hi - lo for lo, hi in bounds]
    assert max(sizes) - min(sizes) <= 1


def test_block_bounds_respects_nonzero_start():
    bounds = [block_bounds(100, 140, r, 4) for r in range(4)]
    assert bounds[0][0] == 100 and bounds[-1][1] == 140
    assert [hi - lo for lo, hi in bounds] == [10, 10, 10, 10]


def test_block_bounds_rejects_bad_rank():
    with pytest.raises(ValueError):
        block_bounds(0, 10, 3, 3)


# --------------------------------------------------------------------------- #
# resolve_devices
# --------------------------------------------------------------------------- #
def test_resolve_devices_explicit_list():
    devs = resolve_devices(["cpu", "cpu"])
    assert devs == [torch.device("cpu"), torch.device("cpu")]


def test_resolve_devices_int_gives_cuda_indices():
    devs = resolve_devices(3)
    assert devs == [
        torch.device("cuda:0"),
        torch.device("cuda:1"),
        torch.device("cuda:2"),
    ]


def test_resolve_devices_rejects_empty():
    with pytest.raises(ValueError):
        resolve_devices([])
    with pytest.raises(ValueError):
        resolve_devices(0)


# --------------------------------------------------------------------------- #
# merge_streams
# --------------------------------------------------------------------------- #
def _fake_stream(path: Path, events: list[int]) -> None:
    lines = [
        "CrystFEL stream format 2.3",
        "Generated by probixi",
        "----- Begin geometry file -----",
        "GEOM CONTENT",
        "----- End geometry file -----",
    ]
    for i, ev in enumerate(events, start=1):
        lines += [
            "----- Begin chunk -----",
            "Image filename: run.h5",
            f"Event: //{ev}",
            f"Image serial number: {i}",
            "----- End chunk -----",
        ]
    path.write_text("\n".join(lines) + "\n")


def test_merge_streams_single_header_and_global_serials(tmp_path):
    p0, p1 = tmp_path / "o.rank0", tmp_path / "o.rank1"
    _fake_stream(p0, [0, 1])
    _fake_stream(p1, [2, 3, 4])
    out = tmp_path / "merged.stream"

    n = merge_streams([p0, p1], out)
    txt = out.read_text()

    assert n == 5
    assert txt.count("CrystFEL stream format") == 1  # header once
    assert txt.count("Begin geometry file") == 1  # geometry once
    assert txt.count("Begin chunk") == 5
    serials = [
        int(ln.split(":")[1])
        for ln in txt.splitlines()
        if ln.startswith("Image serial")
    ]
    assert serials == [1, 2, 3, 4, 5]  # renumbered globally, monotonic
    events = [
        int(ln.split("//")[1]) for ln in txt.splitlines() if ln.startswith("Event:")
    ]
    assert events == [0, 1, 2, 3, 4]  # frame order preserved (contiguous blocks)


def test_merge_streams_handles_empty_and_missing_parts(tmp_path):
    p0, p1, p2 = tmp_path / "o.rank0", tmp_path / "o.rank1", tmp_path / "o.rank2"
    _fake_stream(p0, [0])
    _fake_stream(p1, [])  # a block that indexed nothing: header only
    # p2 never created (a crashed/absent worker)
    out = tmp_path / "merged.stream"

    n = merge_streams([p0, p1, p2], out)
    txt = out.read_text()
    assert n == 1
    assert txt.count("CrystFEL stream format") == 1
    assert txt.count("Begin chunk") == 1


def test_merge_streams_skips_zero_byte_first_part(tmp_path):
    # a worker that crashed after truncating its file to 0 bytes must not eat the
    # header: the merged stream still recovers its header from the next valid part
    p0, p1 = tmp_path / "o.rank0", tmp_path / "o.rank1"
    p0.write_text("")  # 0-byte part from a crashed rank 0
    _fake_stream(p1, [5, 6])
    out = tmp_path / "merged.stream"

    n = merge_streams([p0, p1], out)
    txt = out.read_text()
    assert n == 2
    assert txt.startswith("CrystFEL stream format")
    assert txt.count("CrystFEL stream format") == 1
    serials = [
        int(ln.split(":")[1])
        for ln in txt.splitlines()
        if ln.startswith("Image serial")
    ]
    assert serials == [1, 2]


def test_validate_cuda_devices_rejects_missing(monkeypatch):
    from probixi import multigpu

    # no CUDA -> requesting a cuda device fails fast (before any spawn)
    monkeypatch.setattr(torch.cuda, "is_available", lambda: False)
    with pytest.raises(RuntimeError):
        multigpu._validate_cuda_devices([torch.device("cuda:0")])
    # cpu-only device lists are always fine
    multigpu._validate_cuda_devices([torch.device("cpu"), torch.device("cpu")])


def test_env_int_rejects_non_integer(monkeypatch):
    from probixi.multigpu import _env_int

    monkeypatch.setenv("RANK", "notanint")
    with pytest.raises(ValueError):
        _env_int("RANK", default=0)
    monkeypatch.setenv("RANK", "3")
    assert _env_int("RANK", default=0) == 3


# --------------------------------------------------------------------------- #
# Real-data integration (runs the actual pipeline per block, then merges)
# --------------------------------------------------------------------------- #
def _has_run_data() -> bool:
    return RUN_LST.is_file() and RUN_GEOM.is_file() and RUN_CELL.is_file()


@pytest.mark.slow
def test_run_block_covers_disjoint_ranges_and_merges(tmp_path):
    if not _has_run_data():
        pytest.skip("no test_data/run1.lst run available")
    cfg = BlockConfig(
        list_file=str(RUN_LST),
        geometry_file=str(RUN_GEOM),
        cell_file=str(RUN_CELL),
        start=0,
        stop=8,
        seed_frames=4,
        batch_size=4,
        threads=2,
        quiet=True,
    )
    # Drive both ranks in-process (no spawn) to keep the test fast + robust.
    parts = [tmp_path / "o.rank0", tmp_path / "o.rank1"]
    s0 = run_block(0, 2, "cpu", cfg, parts[0])
    s1 = run_block(1, 2, "cpu", cfg, parts[1])

    # contiguous, disjoint blocks covering the whole [0, 8) range
    assert (s0["lo"], s0["hi"]) == (0, 4)
    assert (s1["lo"], s1["hi"]) == (4, 8)
    assert s0["frames"] + s1["frames"] == 8

    out = tmp_path / "merged.stream"
    merge_streams(parts, out)
    txt = out.read_text()
    assert txt.count("CrystFEL stream format") == 1
    serials = [
        int(ln.split(":")[1])
        for ln in txt.splitlines()
        if ln.startswith("Image serial")
    ]
    assert serials == list(range(1, len(serials) + 1))  # unique + monotonic
