from __future__ import annotations

import math

import pytest
import torch

from probixi.indexer.indexer import IndexResult
from probixi.io.writer import DataOffloader, PeakOffloader
from probixi.peakfinding.peaks.blobs import BlobStats
from probixi.peakfinding.peaks.peakfinder import PeakResult


def _make_index_result(cell) -> IndexResult:
    torch.manual_seed(0)
    # three indexed peaks, one un-indexed, so the crystal block lists only the kept ones
    positions = torch.tensor(
        [[40.0, 55.0], [70.0, 30.0], [90.0, 110.0], [10.0, 12.0]],
        dtype=torch.float64,
    )
    intensities = torch.tensor([1200.0, 800.0, 450.0, 50.0], dtype=torch.float64)
    sigmas = torch.tensor([35.0, 28.0, 21.0, 7.0], dtype=torch.float64)
    indexed_mask = torch.tensor([True, True, True, False])
    hkl = torch.tensor([[1, 0, 0], [0, 1, -1], [2, -1, 3], [0, 0, 0]], dtype=torch.long)
    # A = U @ B; use identity-ish reciprocal basis, distinct columns so a*/b*/c* differ
    A = torch.tensor(
        [[0.016, 0.001, 0.000], [0.000, 0.016, 0.002], [0.001, 0.000, 0.009]],
        dtype=torch.float64,
    )
    U = torch.eye(3, dtype=torch.float64)
    B = A.clone()
    return IndexResult(
        frame_index=0,
        n_peaks=4,
        n_indexed=3,
        rmsd=0.0042,
        A=A,
        U=U,
        B=B,
        cell=cell,
        indexed_mask=indexed_mask,
        hkl=hkl,
        positions=positions,
        intensities=intensities,
        sigmas=sigmas,
        loss_history=torch.zeros(1, dtype=torch.float64),
        scale=None,
    )


def _make_peak_result() -> PeakResult:
    rows = torch.tensor([40.0, 70.0, 90.0], dtype=torch.float64)
    cols = torch.tensor([55.0, 30.0, 110.0], dtype=torch.float64)
    isum = torch.tensor([1200.0, 800.0, 450.0], dtype=torch.float64)
    n = rows.numel()
    el = torch.arange(1, n + 1, dtype=torch.long)
    z = torch.zeros(n, dtype=torch.float64)
    stats = BlobStats(
        label_id=el,
        size=torch.full((n,), 9, dtype=torch.long),
        row_centroid=rows,
        col_centroid=cols,
        bbox_r0=el,
        bbox_r1=el,
        bbox_c0=el,
        bbox_c1=el,
        intensity_sum=isum,
        intensity_sigma=z,
        intensity_max=z,
        z_max=z,
        log_bf_sum=z,
        posterior_mean=z,
        eccentricity=z,
        peakedness=z,
    )
    return PeakResult(
        frame_index=0,
        scores={},
        labels=torch.zeros(1, 1, dtype=torch.long),
        stats=stats,
        keep=torch.ones(n, dtype=torch.bool),
    )


def _section(lines: list[str], start: str, end: str) -> list[str]:
    i = lines.index(start)
    j = lines.index(end, i)
    return lines[i : j + 1]


def test_written_stream_parses_back(tmp_path, geometry_dict, cell, geom_file):
    out = tmp_path / "indexed.stream"
    with DataOffloader(
        out, geometry=geometry_dict, cell=cell, geometry_file=geom_file
    ) as off:
        off.write(_make_index_result(cell))

    lines = out.read_text().splitlines()
    # header: version line + provenance
    assert lines[0] == "CrystFEL stream format 2.3"
    assert any(line == "Generated by probixi" for line in lines)
    # one chunk, framed by begin/end markers
    assert "----- Begin chunk -----" in lines
    assert "----- End chunk -----" in lines
    assert lines.index("----- Begin chunk -----") < lines.index("----- End chunk -----")


def test_header_embeds_geometry_when_file_passed(
    tmp_path, geometry_dict, cell, geom_file
):
    out = tmp_path / "indexed.stream"
    with DataOffloader(
        out, geometry=geometry_dict, cell=cell, geometry_file=geom_file
    ) as off:
        off.write(_make_index_result(cell))

    text = out.read_text()
    assert "----- Begin geometry file -----" in text
    assert "----- End geometry file -----" in text
    # the actual geometry file contents are embedded verbatim
    embedded = geom_file.read_text().rstrip("\n")
    assert embedded in text


def test_header_omits_geometry_when_no_file(tmp_path, geometry_dict, cell):
    out = tmp_path / "indexed.stream"
    with DataOffloader(out, geometry=geometry_dict, cell=cell) as off:
        off.write(_make_index_result(cell))

    text = out.read_text()
    assert "Begin geometry file" not in text


def test_chunk_reports_peak_count(tmp_path, geometry_dict, cell):
    out = tmp_path / "indexed.stream"
    with DataOffloader(out, geometry=geometry_dict, cell=cell) as off:
        off.write(_make_index_result(cell))

    lines = out.read_text().splitlines()
    assert "num_peaks = 4" in lines
    assert "Peaks from peak search" in lines


def test_crystal_block_has_cell_and_reflections(tmp_path, geometry_dict, cell):
    out = tmp_path / "indexed.stream"
    with DataOffloader(out, geometry=geometry_dict, cell=cell) as off:
        off.write(_make_index_result(cell))

    lines = out.read_text().splitlines()
    crystal = _section(lines, "--- Begin crystal", "--- End crystal")

    # cell parameters: writer emits nm (A / 10) -> 62.23 A -> 6.22300 nm, etc.
    cell_line = next(line for line in crystal if line.startswith("Cell parameters"))
    parsed = cell_line.split()
    a_nm, b_nm, c_nm = float(parsed[2]), float(parsed[3]), float(parsed[4])
    assert parsed[5] == "nm,"
    assert a_nm == pytest.approx(cell.a * 0.1, abs=1e-4)
    assert b_nm == pytest.approx(cell.b * 0.1, abs=1e-4)
    assert c_nm == pytest.approx(cell.c * 0.1, abs=1e-4)
    al, be, ga = float(parsed[6]), float(parsed[7]), float(parsed[8])
    assert parsed[9] == "deg"
    assert al == pytest.approx(math.degrees(cell.alpha), abs=1e-2)
    assert be == pytest.approx(math.degrees(cell.beta), abs=1e-2)
    assert ga == pytest.approx(math.degrees(cell.gamma), abs=1e-2)

    # reciprocal basis lines present and parse to the A columns (A^-1 -> nm^-1)
    astar = next(line for line in crystal if line.startswith("astar = "))
    bstar = next(line for line in crystal if line.startswith("bstar = "))
    cstar = next(line for line in crystal if line.startswith("cstar = "))
    a_vals = [float(t) for t in astar.split()[2:5]]
    assert astar.endswith("nm^-1")
    assert bstar.endswith("nm^-1") and cstar.endswith("nm^-1")
    # column 0 of A, times 10 (A^-1 -> nm^-1)
    assert a_vals == pytest.approx([0.016 * 10, 0.0 * 10, 0.001 * 10], abs=1e-6)

    # only the three indexed peaks become reflections
    num_refl = next(line for line in crystal if line.startswith("num_reflections = "))
    assert int(num_refl.split("=")[1]) == 3

    # parse the hkl reflection rows back
    header_i = crystal.index(
        "   h    k    l          I   sigma(I)       peak background  "
        "fs/px  ss/px panel"
    )
    end_i = crystal.index("End of reflections")
    refl_rows = crystal[header_i + 1 : end_i]
    assert len(refl_rows) == 3
    parsed_hkl = {tuple(int(t) for t in row.split()[:3]) for row in refl_rows}
    assert parsed_hkl == {(1, 0, 0), (0, 1, -1), (2, -1, 3)}


def test_data_offloader_uses_lattice_metadata_from_cell(tmp_path, geometry_dict, cell):
    out = tmp_path / "indexed.stream"
    with DataOffloader(out, geometry=geometry_dict, cell=cell) as off:
        off.write(_make_index_result(cell))

    lines = out.read_text().splitlines()
    assert f"lattice_type = {cell.lattice_type}" in lines
    assert f"centering = {cell.centering}" in lines
    assert f"unique_axis = {cell.unique_axis}" in lines


def test_peak_offloader_writes_peaks_only_chunk(tmp_path, geometry_dict):
    out = tmp_path / "peaks.stream"
    with PeakOffloader(out, geometry=geometry_dict) as off:
        off.write(_make_peak_result())

    lines = out.read_text().splitlines()
    assert "----- Begin chunk -----" in lines
    assert "----- End chunk -----" in lines
    assert "indexed_by = none" in lines
    assert "num_peaks = 3" in lines
    assert "Peaks from peak search" in lines
    # peaks-only: no crystal block
    assert "--- Begin crystal" not in lines
    assert "num_reflections" not in "\n".join(lines)


def test_write_before_context_manager_raises(tmp_path, geometry_dict, cell):
    off = DataOffloader(tmp_path / "x.stream", geometry=geometry_dict, cell=cell)
    with pytest.raises(RuntimeError):
        off.write(_make_index_result(cell))


def test_peak_offloader_write_before_context_manager_raises(tmp_path, geometry_dict):
    off = PeakOffloader(tmp_path / "x.stream", geometry=geometry_dict)
    with pytest.raises(RuntimeError):
        off.write(_make_peak_result())
