from __future__ import annotations

import math

import pytest
import torch

from probixi.indexer.indexer import IndexResult
from probixi.indexer.lattice import B_to_cell
from probixi.io import read_geometry
from probixi.io.cxi import PeakOffloader
from probixi.io.metadata import H5Info
from probixi.io.writer import DataOffloader, _StreamWriter
from probixi.peakfinding.peaks.blobs import BlobStats
from probixi.peakfinding.peaks.peakfinder import PeakResult


def _make_index_result(cell) -> IndexResult:
    torch.manual_seed(0)
    # three indexed peaks, one un-indexed, so the crystal block lists only the kept ones
    positions = torch.tensor(
        [[40.0, 55.0], [70.0, 30.0], [90.0, 110.0], [10.0, 12.0]],
        dtype=torch.float32,
    )
    intensities = torch.tensor([1200.0, 800.0, 450.0, 50.0], dtype=torch.float32)
    sigmas = torch.tensor([35.0, 28.0, 21.0, 7.0], dtype=torch.float32)
    indexed_mask = torch.tensor([True, True, True, False])
    hkl = torch.tensor([[1, 0, 0], [0, 1, -1], [2, -1, 3], [0, 0, 0]], dtype=torch.long)
    # A = U @ B; use identity-ish reciprocal basis, distinct columns so a*/b*/c* differ
    A = torch.tensor(
        [[0.016, 0.001, 0.000], [0.000, 0.016, 0.002], [0.001, 0.000, 0.009]],
        dtype=torch.float32,
    )
    U = torch.eye(3, dtype=torch.float32)
    B = A.clone()
    return IndexResult(
        frame_index=0,
        n_peaks=4,
        n_indexed=3,
        rmsd=0.0042,
        A=A,
        U=U,
        B=B,
        cell=cell,
        indexed_mask=indexed_mask,
        hkl=hkl,
        positions=positions,
        intensities=intensities,
        sigmas=sigmas,
        loss_history=torch.zeros(1, dtype=torch.float32),
        scale=None,
    )


def _make_peak_result() -> PeakResult:
    rows = torch.tensor([40.0, 70.0, 90.0], dtype=torch.float32)
    cols = torch.tensor([55.0, 30.0, 110.0], dtype=torch.float32)
    isum = torch.tensor([1200.0, 800.0, 450.0], dtype=torch.float32)
    n = rows.numel()
    el = torch.arange(1, n + 1, dtype=torch.long)
    z = torch.zeros(n, dtype=torch.float32)
    stats = BlobStats(
        label_id=el,
        size=torch.full((n,), 9, dtype=torch.long),
        row_centroid=rows,
        col_centroid=cols,
        bbox_r0=el,
        bbox_r1=el,
        bbox_c0=el,
        bbox_c1=el,
        intensity_sum=isum,
        intensity_sigma=z,
        intensity_max=z,
        z_max=z,
        log_bf_sum=z,
        posterior_mean=z,
        eccentricity=z,
        peakedness=z,
        background_sum=z,
    )
    return PeakResult(
        frame_index=0,
        scores={},
        labels=torch.zeros(1, 1, dtype=torch.long),
        stats=stats,
        keep=torch.ones(n, dtype=torch.bool),
    )


def _section(lines: list[str], start: str, end: str) -> list[str]:
    i = lines.index(start)
    j = lines.index(end, i)
    return lines[i : j + 1]


def test_written_stream_parses_back(tmp_path, geometry_dict, cell, geom_file):
    out = tmp_path / "indexed.stream"
    with DataOffloader(
        out, geometry=geometry_dict, cell=cell, geometry_file=geom_file
    ) as off:
        off.write(_make_index_result(cell))

    lines = out.read_text().splitlines()
    # header: version line + provenance
    assert lines[0] == "CrystFEL stream format 2.3"
    assert any(line == "Generated by probixi" for line in lines)
    # one chunk, framed by begin/end markers
    assert "----- Begin chunk -----" in lines
    assert "----- End chunk -----" in lines
    assert lines.index("----- Begin chunk -----") < lines.index("----- End chunk -----")


def test_header_embeds_geometry_when_file_passed(
    tmp_path, geometry_dict, cell, geom_file
):
    out = tmp_path / "indexed.stream"
    with DataOffloader(
        out, geometry=geometry_dict, cell=cell, geometry_file=geom_file
    ) as off:
        off.write(_make_index_result(cell))

    text = out.read_text()
    assert "----- Begin geometry file -----" in text
    assert "----- End geometry file -----" in text
    # the actual geometry file contents are embedded verbatim
    embedded = geom_file.read_text().rstrip("\n")
    assert embedded in text


def test_header_omits_geometry_when_no_file(tmp_path, geometry_dict, cell):
    out = tmp_path / "indexed.stream"
    with DataOffloader(out, geometry=geometry_dict, cell=cell) as off:
        off.write(_make_index_result(cell))

    text = out.read_text()
    assert "Begin geometry file" not in text


def test_chunk_reports_peak_count(tmp_path, geometry_dict, cell):
    out = tmp_path / "indexed.stream"
    with DataOffloader(out, geometry=geometry_dict, cell=cell) as off:
        off.write(_make_index_result(cell))

    lines = out.read_text().splitlines()
    assert "num_peaks = 4" in lines
    assert "Peaks from peak search" in lines


def test_crystal_block_has_cell_and_reflections(tmp_path, geometry_dict, cell):
    out = tmp_path / "indexed.stream"
    result = _make_index_result(cell)
    with DataOffloader(out, geometry=geometry_dict, cell=cell) as off:
        off.write(result)

    lines = out.read_text().splitlines()
    crystal = _section(lines, "--- Begin crystal", "--- End crystal")

    expected = B_to_cell(result.A)
    cell_line = next(line for line in crystal if line.startswith("Cell parameters"))
    parsed = cell_line.split()
    a_nm, b_nm, c_nm = float(parsed[2]), float(parsed[3]), float(parsed[4])
    assert parsed[5] == "nm,"
    assert a_nm == pytest.approx(expected.a * 0.1, abs=1e-4)
    assert b_nm == pytest.approx(expected.b * 0.1, abs=1e-4)
    assert c_nm == pytest.approx(expected.c * 0.1, abs=1e-4)
    al, be, ga = float(parsed[6]), float(parsed[7]), float(parsed[8])
    assert parsed[9] == "deg"
    assert al == pytest.approx(math.degrees(expected.alpha), abs=1e-2)
    assert be == pytest.approx(math.degrees(expected.beta), abs=1e-2)
    assert ga == pytest.approx(math.degrees(expected.gamma), abs=1e-2)
    # recovered, not echoed: this fixture's A does not encode the target cell
    assert a_nm != pytest.approx(cell.a * 0.1, abs=1e-4)

    # reciprocal basis lines present and parse to the A columns (A^-1 -> nm^-1)
    astar = next(line for line in crystal if line.startswith("astar = "))
    bstar = next(line for line in crystal if line.startswith("bstar = "))
    cstar = next(line for line in crystal if line.startswith("cstar = "))
    a_vals = [float(t) for t in astar.split()[2:5]]
    assert astar.endswith("nm^-1")
    assert bstar.endswith("nm^-1") and cstar.endswith("nm^-1")
    # column 0 of A, times 10 (A^-1 -> nm^-1)
    assert a_vals == pytest.approx([0.016 * 10, 0.0 * 10, 0.001 * 10], abs=1e-6)

    # only the three indexed peaks become reflections
    num_refl = next(line for line in crystal if line.startswith("num_reflections = "))
    assert int(num_refl.split("=")[1]) == 3

    # parse the hkl reflection rows back
    header_i = crystal.index(
        "   h    k    l          I   sigma(I)       peak background  "
        "fs/px  ss/px panel"
    )
    end_i = crystal.index("End of reflections")
    refl_rows = crystal[header_i + 1 : end_i]
    assert len(refl_rows) == 3
    parsed_hkl = {tuple(int(t) for t in row.split()[:3]) for row in refl_rows}
    assert parsed_hkl == {(1, 0, 0), (0, 1, -1), (2, -1, 3)}


def test_data_offloader_uses_lattice_metadata_from_cell(tmp_path, geometry_dict, cell):
    out = tmp_path / "indexed.stream"
    with DataOffloader(out, geometry=geometry_dict, cell=cell) as off:
        off.write(_make_index_result(cell))

    lines = out.read_text().splitlines()
    assert f"lattice_type = {cell.lattice_type}" in lines
    assert f"centering = {cell.centering}" in lines
    assert f"unique_axis = {cell.unique_axis}" in lines


def test_peak_offloader_writes_cxi(tmp_path):
    import h5py
    import numpy as np

    raw = tmp_path / "raw.h5"
    with h5py.File(raw, "w") as f:
        f.create_dataset(
            "/entry/data/data", data=np.zeros((2, 128, 128), dtype=np.uint16)
        )
    files = {
        str(raw): H5Info(
            filename=str(raw),
            dataset="/entry/data/data",
            n_frames=2,
            frame_shape=(128, 128),
        )
    }

    out = tmp_path / "cxi_out"
    with PeakOffloader(out, files=files) as off:
        off.write(_make_peak_result())  # frame_index=0 -> event 0

    cxi = out / "raw.cxi"
    assert cxi.exists()
    assert (out / "peaks.lst").read_text().strip() == str(cxi.resolve())

    with h5py.File(cxi, "r") as f:
        base = "/entry_1/result_1"
        assert int(f[f"{base}/nPeaks"][0]) == 3
        assert int(f[f"{base}/nPeaks"][1]) == 0
        # fs = column centroid, ss = row centroid
        assert sorted(f[f"{base}/peakXPosRaw"][0, :3].tolist()) == [30.0, 55.0, 110.0]
        assert sorted(f[f"{base}/peakYPosRaw"][0, :3].tolist()) == [40.0, 70.0, 90.0]
        # external link resolves to the raw image stack (no pixel copy)
        assert f["/entry/data/data"].shape == (2, 128, 128)


def test_write_before_context_manager_raises(tmp_path, geometry_dict, cell):
    off = DataOffloader(tmp_path / "x.stream", geometry=geometry_dict, cell=cell)
    with pytest.raises(RuntimeError):
        off.write(_make_index_result(cell))


def test_peak_offloader_write_before_context_manager_raises(tmp_path):
    off = PeakOffloader(tmp_path / "x.stream")
    with pytest.raises(RuntimeError):
        off.write(_make_peak_result())


# --- peak resolution must come from the panel geometry -----------------------


def _folded_geom_file(tmp_path):
    # Two 4x4 panels stacked in ss in the array, mirrored about the beam in the
    # lab frame: array pixel (ss, fs) on panel 0 and (ss + 4, fs) on panel 1 are
    # at the same scattering angle.
    lines = [
        "clen = 0.1",
        "photon_energy = 12398.0",
        "res = 13333.3",
        "data = /entry/data/data",
        "dim0 = %",
        "dim1 = ss",
        "dim2 = fs",
        "0/min_fs = 0",
        "0/max_fs = 3",
        "0/min_ss = 0",
        "0/max_ss = 3",
        "0/corner_x = 10.0",
        "0/corner_y = -1.5",
        "0/fs = +1.0x +0.0y",
        "0/ss = +0.0x +1.0y",
        "1/min_fs = 0",
        "1/max_fs = 3",
        "1/min_ss = 4",
        "1/max_ss = 7",
        "1/corner_x = -10.0",
        "1/corner_y = -1.5",
        "1/fs = -1.0x +0.0y",
        "1/ss = +0.0x +1.0y",
    ]
    path = tmp_path / "folded.geom"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def _writer_for(geometry_dict):
    w = _StreamWriter.__new__(_StreamWriter)
    w.geometry = geometry_dict
    return w


def test_peak_resolution_uses_panel_geometry(tmp_path):
    geom = read_geometry(_folded_geom_file(tmp_path))
    w = _writer_for(geom.to_dict())

    # mirror pixels are at one scattering angle, so one 1/d
    for ss in range(4):
        for fs in range(4):
            a = w._resolution_nm_inv(float(ss), float(fs))
            b = w._resolution_nm_inv(float(ss + 4), float(fs))
            assert a == pytest.approx(b, rel=1e-5), f"({ss}, {fs}) vs ({ss + 4}, {fs})"

    # and the value is the geometry's: panel 0 (0, 0) sits at lab (+10, -1.5) px
    g = geom.to_dict()
    r_m = math.hypot(10.0, 1.5) * float(g["pixel_size"])
    want = (
        2.0
        * math.sin(0.5 * math.atan2(r_m, float(g["clen"])))
        / (float(g["wavelength"]) * 0.1)
    )
    assert w._resolution_nm_inv(0.0, 0.0) == pytest.approx(want, rel=1e-5)


def test_peak_resolution_is_not_array_radius(tmp_path):
    # the pre-fix formula measured the radius in array coordinates about the
    # beam centre; on a tiled detector that is a different number
    geom = read_geometry(_folded_geom_file(tmp_path))
    g = geom.to_dict()
    w = _writer_for(g)
    bc = g["beam_center"]
    row, col = 4.0, 0.0
    dr = (row - float(bc[0])) * float(g["pixel_size"])
    dc = (col - float(bc[1])) * float(g["pixel_size"])
    array_form = (
        2.0
        * math.sin(0.5 * math.atan2(math.hypot(dr, dc), float(g["clen"])))
        / (float(g["wavelength"]) * 0.1)
    )
    assert w._resolution_nm_inv(row, col) != pytest.approx(array_form, rel=1e-3)


def test_resolution_many_matches_scalar(tmp_path):
    geom = read_geometry(_folded_geom_file(tmp_path))
    w = _writer_for(geom.to_dict())
    pos = [(0.0, 0.0), (2.0, 3.0), (6.0, 1.0)]
    assert w._resolution_nm_inv_many(pos) == pytest.approx(
        [w._resolution_nm_inv(r, c) for r, c in pos], rel=1e-6
    )
    assert w._resolution_nm_inv_many([]) == []


def _with_prediction(result):
    # attach an integrated lattice with the model-background columns
    result.predicted_hkl = torch.tensor([[1, 0, 0], [0, 1, -1]], dtype=torch.long)
    result.predicted_positions = torch.tensor([[40.0, 55.0], [70.0, 30.0]])
    result.predicted_intensities = torch.tensor([1200.0, 800.0])
    result.predicted_sigmas = torch.tensor([35.0, 28.0])
    result.predicted_peak = torch.tensor([300.0, 200.0])
    result.predicted_background = torch.tensor([2.5, 2.25])
    result.predicted_n_pixels = torch.tensor([9.0, 8.0])
    result.predicted_bg_model = torch.tensor([22.5, 18.0])
    result.predicted_bg_model_var = torch.tensor([0.81, 0.64])
    return result


def test_header_records_integration_recipe_and_extra_columns(
    tmp_path, geometry_dict, cell
):
    out = tmp_path / "indexed.stream"
    recipe = dict(
        radii=(1.5, 6.0, 8.6), adu_per_photon=9.9, bg_annulus_pixels=280, aperture="snr"
    )
    with DataOffloader(
        out, geometry=geometry_dict, cell=cell, integration=recipe
    ) as off:
        off.write(_with_prediction(_make_index_result(cell)))

    lines = out.read_text().splitlines()
    first_chunk = lines.index("----- Begin chunk -----")
    header = lines[:first_chunk]
    assert "probixi/int_radius = 1.50,6.00,8.60" in header
    assert "probixi/adu_per_photon = 9.9" in header
    assert "probixi/bg_annulus_pixels = 280" in header
    assert "probixi/aperture = snr" in header
    assert "probixi/reflection_columns = n_pix bg_model bg_model_var" in header

    crystal = _section(lines, "--- Begin crystal", "--- End crystal")
    header_i = next(
        i for i, line in enumerate(crystal) if line.startswith("   h    k    l")
    )
    assert crystal[header_i].split()[-3:] == ["n_pix", "bg_model", "bg_model_var"]
    rows = crystal[header_i + 1 : crystal.index("End of reflections")]
    assert len(rows) == 2
    first = rows[0].split()
    # the ten CrystFEL columns stay in place; the extras follow the panel name
    assert len(first) == 13
    assert first[9] == "0"
    assert int(first[10]) == 9
    assert float(first[11]) == pytest.approx(22.5)
    assert float(first[12]) == pytest.approx(0.81)


def test_reflection_rows_have_ten_columns_without_prediction(
    tmp_path, geometry_dict, cell
):
    out = tmp_path / "indexed.stream"
    with DataOffloader(out, geometry=geometry_dict, cell=cell) as off:
        off.write(_make_index_result(cell))
    lines = out.read_text().splitlines()
    assert not any(line.startswith("probixi/int_radius") for line in lines)
    crystal = _section(lines, "--- Begin crystal", "--- End crystal")
    header_i = next(
        i for i, line in enumerate(crystal) if line.startswith("   h    k    l")
    )
    assert crystal[header_i].split()[-1] == "panel"
    rows = crystal[header_i + 1 : crystal.index("End of reflections")]
    assert all(len(row.split()) == 10 for row in rows)


def test_crystal_records_the_falloff_limit_beside_the_stream_limit(
    tmp_path, geometry_dict, cell
):
    out = tmp_path / "indexed.stream"
    result = _with_prediction(_make_index_result(cell))
    result.diffraction_limit = 3.2  # highest indexed peak, nm^-1
    result.falloff_limit = 2.5  # I/sigma crossing, kept as a diagnostic
    with DataOffloader(out, geometry=geometry_dict, cell=cell) as off:
        off.write(result)
    crystal = _section(
        out.read_text().splitlines(), "--- Begin crystal", "--- End crystal"
    )
    assert any(
        l.startswith("diffraction_resolution_limit = 3.2")
        for l in crystal  # Noqa: E741
    )
    assert "probixi/falloff_limit = 2.500000 nm^-1" in crystal
