from __future__ import annotations

from pathlib import Path

import pytest
import sim
import torch

from probixi.io.geometry import EV_ANGSTROM
from probixi.multigpu import (
    BlockConfig,
    block_bounds,
    merge_streams,
    resolve_devices,
    run_block,
)

FIXTURES = Path(__file__).parent / "fixtures"
CELL_FIXTURE = FIXTURES / "bR.cell"
# small single-panel detector: fast synthetic run, no real data needed
_DET = 256
_CLEN = 0.10
_PIXEL_SIZE = 150e-6
_WAVELENGTH = 1.3


# --------------------------------------------------------------------------- #
# block_bounds
# --------------------------------------------------------------------------- #
@pytest.mark.parametrize(
    "total,world",
    [(810, 4), (10, 3), (7, 8), (100, 1), (1, 1), (0, 3), (256, 8)],
)
def test_block_bounds_covers_range_contiguously(total, world):
    bounds = [block_bounds(0, total, r, world) for r in range(world)]
    # contiguous: each block starts where the previous ended, spanning [0, total)
    assert bounds[0][0] == 0
    assert bounds[-1][1] == total
    for a, b in zip(bounds, bounds[1:]):
        assert a[1] == b[0]
    # full, non-overlapping coverage
    assert sum(hi - lo for lo, hi in bounds) == total
    # balanced: sizes differ by at most one
    sizes = [hi - lo for lo, hi in bounds]
    assert max(sizes) - min(sizes) <= 1


def test_block_bounds_respects_nonzero_start():
    bounds = [block_bounds(100, 140, r, 4) for r in range(4)]
    assert bounds[0][0] == 100 and bounds[-1][1] == 140
    assert [hi - lo for lo, hi in bounds] == [10, 10, 10, 10]


def test_block_bounds_rejects_bad_rank():
    with pytest.raises(ValueError):
        block_bounds(0, 10, 3, 3)


# --------------------------------------------------------------------------- #
# resolve_devices
# --------------------------------------------------------------------------- #
def test_resolve_devices_explicit_list():
    devs = resolve_devices(["cpu", "cpu"])
    assert devs == [torch.device("cpu"), torch.device("cpu")]


def test_resolve_devices_int_gives_cuda_indices():
    devs = resolve_devices(3)
    assert devs == [
        torch.device("cuda:0"),
        torch.device("cuda:1"),
        torch.device("cuda:2"),
    ]


def test_resolve_devices_rejects_empty():
    with pytest.raises(ValueError):
        resolve_devices([])
    with pytest.raises(ValueError):
        resolve_devices(0)


# --------------------------------------------------------------------------- #
# merge_streams
# --------------------------------------------------------------------------- #
def _fake_stream(path: Path, events: list[int]) -> None:
    lines = [
        "CrystFEL stream format 2.3",
        "Generated by probixi",
        "----- Begin geometry file -----",
        "GEOM CONTENT",
        "----- End geometry file -----",
    ]
    for i, ev in enumerate(events, start=1):
        lines += [
            "----- Begin chunk -----",
            "Image filename: run.h5",
            f"Event: //{ev}",
            f"Image serial number: {i}",
            "----- End chunk -----",
        ]
    path.write_text("\n".join(lines) + "\n")


def test_merge_streams_single_header_and_global_serials(tmp_path):
    p0, p1 = tmp_path / "o.rank0", tmp_path / "o.rank1"
    _fake_stream(p0, [0, 1])
    _fake_stream(p1, [2, 3, 4])
    out = tmp_path / "merged.stream"

    n = merge_streams([p0, p1], out)
    txt = out.read_text()

    assert n == 5
    assert txt.count("CrystFEL stream format") == 1  # header once
    assert txt.count("Begin geometry file") == 1  # geometry once
    assert txt.count("Begin chunk") == 5
    serials = [
        int(ln.split(":")[1])
        for ln in txt.splitlines()
        if ln.startswith("Image serial")
    ]
    assert serials == [1, 2, 3, 4, 5]  # renumbered globally, monotonic
    events = [
        int(ln.split("//")[1]) for ln in txt.splitlines() if ln.startswith("Event:")
    ]
    assert events == [0, 1, 2, 3, 4]  # frame order preserved (contiguous blocks)


def test_merge_streams_handles_empty_and_missing_parts(tmp_path):
    p0, p1, p2 = tmp_path / "o.rank0", tmp_path / "o.rank1", tmp_path / "o.rank2"
    _fake_stream(p0, [0])
    _fake_stream(p1, [])  # a block that indexed nothing: header only
    # p2 never created (a crashed/absent worker)
    out = tmp_path / "merged.stream"

    n = merge_streams([p0, p1, p2], out)
    txt = out.read_text()
    assert n == 1
    assert txt.count("CrystFEL stream format") == 1
    assert txt.count("Begin chunk") == 1


def test_merge_streams_skips_zero_byte_first_part(tmp_path):
    # a worker that crashed after truncating its file to 0 bytes must not eat the
    # header: the merged stream still recovers its header from the next valid part
    p0, p1 = tmp_path / "o.rank0", tmp_path / "o.rank1"
    p0.write_text("")  # 0-byte part from a crashed rank 0
    _fake_stream(p1, [5, 6])
    out = tmp_path / "merged.stream"

    n = merge_streams([p0, p1], out)
    txt = out.read_text()
    assert n == 2
    assert txt.startswith("CrystFEL stream format")
    assert txt.count("CrystFEL stream format") == 1
    serials = [
        int(ln.split(":")[1])
        for ln in txt.splitlines()
        if ln.startswith("Image serial")
    ]
    assert serials == [1, 2]


def test_validate_cuda_devices_rejects_missing(monkeypatch):
    from probixi import multigpu

    # no CUDA -> requesting a cuda device fails fast (before any spawn)
    monkeypatch.setattr(torch.cuda, "is_available", lambda: False)
    with pytest.raises(RuntimeError):
        multigpu._validate_cuda_devices([torch.device("cuda:0")])
    # cpu-only device lists are always fine
    multigpu._validate_cuda_devices([torch.device("cpu"), torch.device("cpu")])


def test_env_int_rejects_non_integer(monkeypatch):
    from probixi.multigpu import _env_int

    monkeypatch.setenv("RANK", "notanint")
    with pytest.raises(ValueError):
        _env_int("RANK", default=0)
    monkeypatch.setenv("RANK", "3")
    assert _env_int("RANK", default=0) == 3


# --------------------------------------------------------------------------- #
# Integration: run the actual per-block pipeline on a SYNTHETIC run, then merge.
# Indexing correctness itself is covered by test_pipeline_cli; here we exercise the
# multi-GPU-specific orchestration (block sub-range, per-rank offload, stats, merge).
# --------------------------------------------------------------------------- #
def _sim_geom_text() -> str:
    # single centred panel; beam_center=(-corner_y,-corner_x), res=1/pixel_size
    bc = (_DET - 1) / 2.0
    return (
        f"clen = {_CLEN}\n"
        f"photon_energy = {EV_ANGSTROM / _WAVELENGTH}\n"
        f"res = {1.0 / _PIXEL_SIZE}\n"
        "max_adu = 65535\n"
        "data = /entry/data/data\n"
        "0/min_fs = 0\n"
        "0/min_ss = 0\n"
        f"0/max_fs = {_DET - 1}\n"
        f"0/max_ss = {_DET - 1}\n"
        f"0/corner_x = {-bc}\n"
        f"0/corner_y = {-bc}\n"
        "0/fs = +1.0x +0.0y\n"
        "0/ss = +0.0x +1.0y\n"
    )


def _synthetic_noise_run(tmp_path: Path) -> tuple[Path, Path]:
    # 8 signal-free frames written as an HDF5 stack + a .lst (absolute paths, so the
    # run is CWD-independent), plus a matching single-panel geometry.
    geom_path = tmp_path / "sim.geom"
    geom_path.write_text(_sim_geom_text(), encoding="utf-8")
    noise = sim.simulate_noise_frames((_DET, _DET), 8, seed=100)
    _, lst_path = sim.write_run(tmp_path / "run", noise)
    return lst_path, geom_path


def test_run_block_covers_disjoint_ranges_and_merges(tmp_path):
    lst_path, geom_path = _synthetic_noise_run(tmp_path)
    cfg = BlockConfig(
        list_file=str(lst_path),
        geometry_file=str(geom_path),
        cell_file=str(CELL_FIXTURE),
        start=0,
        stop=8,
        seed_frames=4,
        batch_size=4,
        threads=2,
        quiet=True,
    )
    # drive both ranks in-process (no spawn) to keep the test fast + robust
    parts = [tmp_path / "o.rank0", tmp_path / "o.rank1"]
    s0 = run_block(0, 2, "cpu", cfg, parts[0])
    s1 = run_block(1, 2, "cpu", cfg, parts[1])

    # contiguous, disjoint blocks covering the whole [0, 8) range
    assert (s0["lo"], s0["hi"]) == (0, 4)
    assert (s1["lo"], s1["hi"]) == (4, 8)
    assert s0["frames"] == 4 and s1["frames"] == 4
    # each rank drops a stats sidecar next to its part
    assert Path(f"{parts[0]}.stats.json").is_file()
    assert Path(f"{parts[1]}.stats.json").is_file()

    # the per-rank parts merge into one well-formed stream: a single header and
    # globally renumbered, monotonic serials (empty is fine -- noise indexes nothing)
    out = tmp_path / "merged.stream"
    merge_streams(parts, out)
    txt = out.read_text()
    assert txt.count("CrystFEL stream format") == 1
    serials = [
        int(ln.split(":")[1])
        for ln in txt.splitlines()
        if ln.startswith("Image serial")
    ]
    assert serials == list(range(1, len(serials) + 1))  # unique + monotonic
