from __future__ import annotations

import math
from pathlib import Path
from typing import TYPE_CHECKING, Optional, Union

from .geometry import EV_ANGSTROM

if TYPE_CHECKING:
    from ..indexer.indexer import IndexResult
    from .cell import CellParams

PathLike = Union[str, Path]

STREAM_VERSION = "CrystFEL stream format 2.3"
A_INV_TO_NM_INV = 10.0  # 1 A^-1 = 10 nm^-1
A_TO_NM = 0.1  # 1 A = 0.1 nm


class DataOffloader:
    """Write ``IndexResult``s to a CrystFEL-style ``.stream`` file.

    Use as a context manager; the instance is itself the per-frame writer
    expected by ``IndexStream.to_stream`` (``__call__`` forwards to ``write``)::

        with DataOffloader(out, geometry=geom, cell=cell, files=files) as off:
            stream.to_stream(off)

    Parameters
    ----------
    path : str or Path
        Destination stream file.
    geometry : dict
        Indexer geometry (``beam_center``, ``clen``, ``pixel_size``,
        ``wavelength``, and -- when available -- the parsed ``panels``).
    cell : CellParams, optional
        Target unit cell; the source of truth for per-crystal parameters and
        symmetry since indexing fixes the cell to this target.
    geometry_file : str or Path, optional
        Geometry file embedded verbatim in the stream header when present.
    files : dict, optional
        Loader file map, used to resolve a global frame index back to its
        source file and within-file event number.
    indexer_name : str, default "probixi"
        Value written for ``indexed_by``.
    panel : str, default "0"
        Fallback panel name when a peak falls outside every geometry panel
        (or when the geometry carries no panel definitions).
    """

    def __init__(
        self,
        path: PathLike,
        geometry: dict,
        *,
        cell: Optional["CellParams"] = None,
        geometry_file: Optional[PathLike] = None,
        files: Optional[dict] = None,
        indexer_name: str = "probixi",
        panel: str = "0",
    ):
        self.path = Path(path)
        self.geometry = geometry
        self.cell = cell
        self.indexer_name = indexer_name
        self.panel = panel
        self._panels = _panel_bounds(geometry.get("panels"))
        self._geometry_file = Path(geometry_file) if geometry_file else None
        self._ranges = _build_frame_ranges(files)
        self._fh = None
        self._serial = 0

    def __enter__(self) -> "DataOffloader":
        self._fh = self.path.open("w")
        self._write_header()
        return self

    def __exit__(self, *exc) -> None:
        if self._fh is not None:
            self._fh.close()
            self._fh = None

    def __call__(self, result: "IndexResult") -> None:
        self.write(result)

    def write(self, result: "IndexResult") -> None:
        """Append one indexed frame to the stream as a CrystFEL chunk."""
        if self._fh is None:
            raise RuntimeError("DataOffloader must be used as a context manager")
        self._serial += 1
        self._fh.write(self._format_chunk(result))

    def _write_header(self) -> None:
        assert self._fh is not None
        lines = [STREAM_VERSION, f"Generated by {self.indexer_name}"]
        if self._geometry_file and self._geometry_file.is_file():
            lines.append("----- Begin geometry file -----")
            lines.append(self._geometry_file.read_text().rstrip("\n"))
            lines.append("----- End geometry file -----")
        self._fh.write("\n".join(lines) + "\n")

    def _format_chunk(self, result: "IndexResult") -> str:
        g = self.geometry
        wavelength_A = float(g["wavelength"])
        photon_eV = EV_ANGSTROM / wavelength_A
        filename, event = self._locate(result.frame_index)

        positions = result.positions.detach().cpu().tolist()
        intensities = result.intensities.detach().cpu().tolist()
        sigmas = result.sigmas.detach().cpu().tolist()
        indexed = result.indexed_mask.detach().cpu().tolist()
        hkl = result.hkl.detach().cpu().tolist()
        A = result.A.detach().cpu().tolist()

        peak_rows: list[str] = []
        max_recip = 0.0
        for (row, col), intensity in zip(positions, intensities):
            recip = self._resolution_nm_inv(row, col)
            max_recip = max(max_recip, recip)
            # fs = column (fast scan), ss = row (slow scan)
            peak_rows.append(
                f"{col:7.2f} {row:7.2f} {recip:10.2f} {intensity:10.2f}   "
                f"{self._panel_for(col, row)}"
            )

        out: list[str] = [
            "----- Begin chunk -----",
            f"Image filename: {filename}",
            f"Event: //{event}",
            f"Image serial number: {self._serial}",
            # only indexed frames are written, so every chunk is a hit
            "hit = 1",
            f"indexed_by = {self.indexer_name}",
            "n_indexing_tries = 1",
            f"photon_energy_eV = {photon_eV:.2f}",
            # divergence/bandwidth not modelled; CrystFEL defaults
            "beam_divergence = 0.00e+00 rad",
            "beam_bandwidth = 1.00e-08 (fraction)",
            f"average_camera_length = {float(g['clen']):.6f} m",
            f"num_peaks = {result.n_peaks}",
            "num_saturated_peaks = 0",
            f"peak_resolution = {_resolution_line(max_recip)}",
            "Peaks from peak search",
            "  fs/px   ss/px (1/d)/nm^-1   Intensity  Panel",
            *peak_rows,
            "End of peak list",
        ]

        out += self._format_crystal(
            result, A, hkl, indexed, positions, intensities, sigmas
        )
        out.append("----- End chunk -----")
        return "\n".join(out) + "\n"

    def _format_crystal(
        self,
        result: "IndexResult",
        A: list,
        hkl: list,
        indexed: list,
        positions: list,
        intensities: list,
        sigmas: list,
    ) -> list[str]:
        # Indexing fixes the cell to the target, so prefer it over the recovered
        # cell for parameters and lattice_type/centering/unique_axis.
        cell = self.cell or result.cell
        a_nm = cell.a * A_TO_NM
        b_nm = cell.b * A_TO_NM
        c_nm = cell.c * A_TO_NM
        al, be, ga = (
            math.degrees(cell.alpha),
            math.degrees(cell.beta),
            math.degrees(cell.gamma),
        )
        # columns of A are reciprocal basis vectors a*/b*/c* (A^-1 -> nm^-1)
        astar = [A[r][0] * A_INV_TO_NM_INV for r in range(3)]
        bstar = [A[r][1] * A_INV_TO_NM_INV for r in range(3)]
        cstar = [A[r][2] * A_INV_TO_NM_INV for r in range(3)]

        # Predicted-and-integrated lattice when available, else observed peaks
        if result.predicted_hkl is not None:
            p_pos = result.predicted_positions.detach().cpu().tolist()
            p_hkl = result.predicted_hkl.detach().cpu().tolist()
            p_int = result.predicted_intensities.detach().cpu().tolist()
            p_sig = result.predicted_sigmas.detach().cpu().tolist()
            p_pk = result.predicted_peak.detach().cpu().tolist()
            p_bg = result.predicted_background.detach().cpu().tolist()
            refl = list(zip(p_pos, p_hkl, p_int, p_sig, p_pk, p_bg))
        else:
            refl = [
                (rc, hk, i, s, 0.0, 0.0)
                for rc, hk, keep, i, s in zip(
                    positions, hkl, indexed, intensities, sigmas
                )
                if keep
            ]

        max_recip = max(
            (self._resolution_nm_inv(row, col) for (row, col), *_ in refl),
            default=0.0,
        )

        lines = [
            "--- Begin crystal",
            f"Cell parameters {a_nm:.5f} {b_nm:.5f} {c_nm:.5f} nm, "
            f"{al:.2f} {be:.2f} {ga:.2f} deg",
            "astar = {:+.7f} {:+.7f} {:+.7f} nm^-1".format(*astar),
            "bstar = {:+.7f} {:+.7f} {:+.7f} nm^-1".format(*bstar),
            "cstar = {:+.7f} {:+.7f} {:+.7f} nm^-1".format(*cstar),
            f"lattice_type = {cell.lattice_type or 'triclinic'}",
            f"centering = {cell.centering or 'P'}",
            f"unique_axis = {cell.unique_axis or '?'}",
            # orientation-only refinement; detector position is never refined
            "predict_refine/det_shift x = 0.000000 y = 0.000000 mm",
            f"probixi/rmsd = {result.rmsd:.6f} A^-1",
        ]
        if result.scale is not None:
            lines.append(
                f"probixi/scale = {result.scale:.5f} {result.scale_sigma or 0.0:.5f}"
            )
        lines += [
            f"diffraction_resolution_limit = {_resolution_line(max_recip)}",
            f"num_reflections = {len(refl)}",
            "num_saturated_reflections = 0",
            "num_implausible_reflections = 0",
            "Reflections measured after indexing",
            "   h    k    l          I   sigma(I)       peak background  "
            "fs/px  ss/px panel",
        ]
        for (row, col), (h, k, l), intensity, sigma, peak, background in refl:
            lines.append(
                f"{int(h):4d} {int(k):4d} {int(l):4d} {intensity:10.2f} "
                f"{sigma:10.2f} {peak:10.2f} {background:10.2f} "
                f"{col:6.1f} {row:6.1f} {self._panel_for(col, row)}"
            )
        lines += ["End of reflections", "--- End crystal"]
        return lines

    def _resolution_nm_inv(self, row: float, col: float) -> float:
        # q = 1/d = 2 sin(theta)/lambda; lambda_nm = 0.1 lambda_A -> nm^-1
        g = self.geometry
        bc = g["beam_center"]
        dr = (row - float(bc[0])) * float(g["pixel_size"])
        dc = (col - float(bc[1])) * float(g["pixel_size"])
        two_theta = math.atan2(math.hypot(dr, dc), float(g["clen"]))
        return 2.0 * math.sin(0.5 * two_theta) / (float(g["wavelength"]) * 0.1)

    def _panel_for(self, fs: float, ss: float) -> str:
        # Panel containing (fs, ss), else the fallback name.
        for name, min_fs, max_fs, min_ss, max_ss in self._panels:
            if min_fs <= fs <= max_fs and min_ss <= ss <= max_ss:
                return name
        return self.panel

    def _locate(self, frame_index: Optional[int]) -> tuple[str, int]:
        if frame_index is None:
            return "unknown", 0
        for start, stop, fname in self._ranges:
            if start <= frame_index < stop:
                return fname, frame_index - start
        return "unknown", int(frame_index)


def _resolution_line(recip_nm_inv: float) -> str:
    # CrystFEL '<X> nm^-1 or <Y> A' from 1/d in nm^-1 (d_A = 10 / recip).
    if recip_nm_inv <= 0.0:
        return "0.000000 nm^-1 or inf A"
    d_angstrom = 10.0 / recip_nm_inv
    return f"{recip_nm_inv:.6f} nm^-1 or {d_angstrom:.6f} A"


def _panel_bounds(
    panels: Optional[dict],
) -> list[tuple[str, int, int, int, int]]:
    # Flatten panels to (name, min_fs, max_fs, min_ss, max_ss)
    out: list[tuple[str, int, int, int, int]] = []
    if not panels:
        return out
    for name, data in panels.items():
        try:
            out.append(
                (
                    str(name),
                    int(data["min_fs"]),
                    int(data["max_fs"]),
                    int(data["min_ss"]),
                    int(data["max_ss"]),
                )
            )
        except (KeyError, TypeError, ValueError):
            continue
    return out


def _build_frame_ranges(files: Optional[dict]) -> list[tuple[int, int, str]]:
    # Cumulative (start, stop, filename) ranges over files in load order.
    ranges: list[tuple[int, int, str]] = []
    if not files:
        return ranges
    start = 0
    for fname, info in files.items():
        n = int(getattr(info, "n_frames", 0))
        ranges.append((start, start + n, str(getattr(info, "filename", fname))))
        start += n
    return ranges
