from __future__ import annotations

import math
from pathlib import Path
from typing import TYPE_CHECKING, Optional, Union

import torch

from ..indexer.lattice import B_to_cell
from .geometry import EV_ANGSTROM

if TYPE_CHECKING:
    from ..indexer.indexer import IndexResult
    from .cell import CellParams

PathLike = Union[str, Path]

STREAM_VERSION = "CrystFEL stream format 2.3"
A_INV_TO_NM_INV = 10.0  # 1 A^-1 = 10 nm^-1
A_TO_NM = 0.1  # 1 A = 0.1 nm
DEFAULT_PROFILE_RADIUS_NM_INV = 0.002
PROFILE_RADIUS_RMSD_FACTOR = 0.6
PROFILE_RADIUS_MIN_NM_INV = 0.0005
PROFILE_RADIUS_MAX_NM_INV = 0.020


def _profile_radius_nm_inv(rmsd_a_inv: float) -> float:
    if not math.isfinite(rmsd_a_inv) or rmsd_a_inv <= 0.0:
        return DEFAULT_PROFILE_RADIUS_NM_INV
    r = PROFILE_RADIUS_RMSD_FACTOR * rmsd_a_inv * A_INV_TO_NM_INV
    return min(max(r, PROFILE_RADIUS_MIN_NM_INV), PROFILE_RADIUS_MAX_NM_INV)


class _StreamWriter:
    """Shared CrystFEL ``.stream`` writing machinery.

    Owns the file handle, the stream header, and the geometry-derived helpers
    (panel lookup, resolution, frame -> source-file mapping) used to format the
    peak-search portion of every chunk. Concrete writers implement
    :meth:`write` and reuse :meth:`_peak_search_lines`.

    Parameters
    ----------
    path : str or Path
        Destination stream file.
    geometry : dict
        Indexer geometry (``beam_center``, ``clen``, ``pixel_size``,
        ``wavelength``, and -- when available -- the parsed ``panels``).
    geometry_file : str or Path, optional
        Geometry file embedded verbatim in the stream header when present.
    files : dict, optional
        Loader file map, used to resolve a global frame index back to its
        source file and within-file event number.
    indexer_name : str, default "probixi"
        Value written for ``Generated by``.
    panel : str, default "0"
        Fallback panel name when a peak falls outside every geometry panel
        (or when the geometry carries no panel definitions).
    """

    def __init__(
        self,
        path: PathLike,
        geometry: dict,
        *,
        geometry_file: Optional[PathLike] = None,
        files: Optional[dict] = None,
        indexer_name: str = "probixi",
        panel: str = "0",
    ):
        self.path = Path(path)
        self.geometry = geometry
        self.indexer_name = indexer_name
        self.panel = panel
        self._panels = _panel_bounds(geometry.get("panels"))
        self._geometry_file = Path(geometry_file) if geometry_file else None
        self._ranges = _build_frame_ranges(files)
        self._fh = None
        self._serial = 0

    def __enter__(self) -> "_StreamWriter":
        self._fh = self.path.open("w")
        self._write_header()
        return self

    def __exit__(self, *exc) -> None:
        if self._fh is not None:
            self._fh.close()
            self._fh = None

    def __call__(self, result) -> None:
        self.write(result)

    def write(self, result) -> None:
        """Append one frame to the stream. Implemented by subclasses."""
        raise NotImplementedError

    def _write_header(self) -> None:
        assert self._fh is not None
        lines = [STREAM_VERSION, f"Generated by {self.indexer_name}"]
        if self._geometry_file and self._geometry_file.is_file():
            lines.append("----- Begin geometry file -----")
            lines.append(self._geometry_file.read_text().rstrip("\n"))
            lines.append("----- End geometry file -----")
        self._fh.write("\n".join(lines) + "\n")

    def _peak_search_lines(
        self,
        frame_index: Optional[int],
        positions,
        intensities,
        num_peaks: int,
        indexed_by: str,
    ) -> list[str]:
        g = self.geometry
        photon_eV = EV_ANGSTROM / float(g["wavelength"])
        filename, event = self._locate(frame_index)

        peak_rows: list[str] = []
        max_recip = 0.0
        for (row, col), intensity in zip(positions, intensities):
            recip = self._resolution_nm_inv(row, col)
            max_recip = max(max_recip, recip)
            # fs = column (fast scan), ss = row (slow scan)
            peak_rows.append(
                f"{col:7.2f} {row:7.2f} {recip:10.2f} {intensity:10.2f}   "
                f"{self._panel_for(col, row)}"
            )

        return [
            "----- Begin chunk -----",
            f"Image filename: {filename}",
            f"Event: //{event}",
            f"Image serial number: {self._serial}",
            # only frames worth writing are emitted, so every chunk is a hit
            "hit = 1",
            f"indexed_by = {indexed_by}",
            "n_indexing_tries = 1",
            f"photon_energy_eV = {photon_eV:.2f}",
            # divergence/bandwidth not modelled; CrystFEL defaults
            "beam_divergence = 0.00e+00 rad",
            "beam_bandwidth = 1.00e-08 (fraction)",
            f"average_camera_length = {float(g['clen']):.6f} m",
            f"num_peaks = {num_peaks}",
            "num_saturated_peaks = 0",
            f"peak_resolution = {_resolution_line(max_recip)}",
            "Peaks from peak search",
            "  fs/px   ss/px (1/d)/nm^-1   Intensity  Panel",
            *peak_rows,
            "End of peak list",
        ]

    def _resolution_nm_inv(self, row: float, col: float) -> float:
        # q = 1/d = 2 sin(theta)/lambda; lambda_nm = 0.1 lambda_A -> nm^-1
        g = self.geometry
        bc = g["beam_center"]
        dr = (row - float(bc[0])) * float(g["pixel_size"])
        dc = (col - float(bc[1])) * float(g["pixel_size"])
        two_theta = math.atan2(math.hypot(dr, dc), float(g["clen"]))
        return 2.0 * math.sin(0.5 * two_theta) / (float(g["wavelength"]) * 0.1)

    def _panel_for(self, fs: float, ss: float) -> str:
        # Panel containing (fs, ss), else the fallback name.
        for name, min_fs, max_fs, min_ss, max_ss in self._panels:
            if min_fs <= fs <= max_fs and min_ss <= ss <= max_ss:
                return name
        return self.panel

    def _locate(self, frame_index: Optional[int]) -> tuple[str, int]:
        if frame_index is None:
            return "unknown", 0
        for start, stop, fname in self._ranges:
            if start <= frame_index < stop:
                return fname, frame_index - start
        return "unknown", int(frame_index)


class DataOffloader(_StreamWriter):
    """Write ``IndexResult``s to a CrystFEL-style ``.stream`` file.

    Use as a context manager; the instance is itself the per-frame writer
    expected by ``IndexStream.to_stream`` (``__call__`` forwards to ``write``)::

        with DataOffloader(out, geometry=geom, cell=cell, files=files) as off:
            stream.to_stream(off)

    Parameters
    ----------
    path : str or Path
        Destination stream file.
    geometry : dict
        Indexer geometry (``beam_center``, ``clen``, ``pixel_size``,
        ``wavelength``, and -- when available -- the parsed ``panels``).
    cell : CellParams, optional
        Target unit cell; supplies the symmetry labels (lattice_type, centering,
        unique_axis). Per-crystal cell parameters are recovered from each
        solution's orientation matrix.
    geometry_file : str or Path, optional
        Geometry file embedded verbatim in the stream header when present.
    files : dict, optional
        Loader file map, used to resolve a global frame index back to its
        source file and within-file event number.
    indexer_name : str, default "probixi"
        Value written for ``Generated by``. The per-crystal
        ``indexed_by`` is always ``fromfile`` so CrystFEL parses it as a known
        indexing method.
    panel : str, default "0"
        Fallback panel name when a peak falls outside every geometry panel
        (or when the geometry carries no panel definitions).
    """

    def __init__(
        self,
        path: PathLike,
        geometry: dict,
        *,
        cell: Optional["CellParams"] = None,
        geometry_file: Optional[PathLike] = None,
        files: Optional[dict] = None,
        indexer_name: str = "probixi",
        panel: str = "0",
    ):
        super().__init__(
            path,
            geometry,
            geometry_file=geometry_file,
            files=files,
            indexer_name=indexer_name,
            panel=panel,
        )
        self.cell = cell

    def write(self, result: "IndexResult") -> None:
        """Append one indexed frame to the stream as a CrystFEL chunk."""
        if self._fh is None:
            raise RuntimeError("DataOffloader must be used as a context manager")
        self._serial += 1
        self._fh.write(self._format_chunk(result))

    def _format_chunk(self, result: "IndexResult") -> str:
        positions = result.positions.detach().cpu().tolist()
        intensities = result.intensities.detach().cpu().tolist()
        sigmas = result.sigmas.detach().cpu().tolist()
        indexed = result.indexed_mask.detach().cpu().tolist()
        hkl = result.hkl.detach().cpu().tolist()
        A = result.A.detach().cpu().tolist()

        out = self._peak_search_lines(
            result.frame_index,
            positions,
            intensities,
            result.n_peaks,
            "fromfile",
        )
        out += self._format_crystal(
            result, A, hkl, indexed, positions, intensities, sigmas
        )
        out.append("----- End chunk -----")
        return "\n".join(out) + "\n"

    def _format_crystal(
        self,
        result: "IndexResult",
        A: list,
        hkl: list,
        indexed: list,
        positions: list,
        intensities: list,
        sigmas: list,
    ) -> list[str]:
        recovered = B_to_cell(result.A)
        cell = self.cell or result.cell
        a_nm = recovered.a * A_TO_NM
        b_nm = recovered.b * A_TO_NM
        c_nm = recovered.c * A_TO_NM
        al, be, ga = (
            math.degrees(recovered.alpha),
            math.degrees(recovered.beta),
            math.degrees(recovered.gamma),
        )
        # columns of A are reciprocal basis vectors a*/b*/c* (A^-1 -> nm^-1)
        astar = [A[r][0] * A_INV_TO_NM_INV for r in range(3)]
        bstar = [A[r][1] * A_INV_TO_NM_INV for r in range(3)]
        cstar = [A[r][2] * A_INV_TO_NM_INV for r in range(3)]

        # Predicted-and-integrated lattice when available, else observed peaks
        if result.predicted_hkl is not None:
            p_pos = result.predicted_positions.detach().cpu().tolist()
            p_hkl = result.predicted_hkl.detach().cpu().tolist()
            p_int, p_sig, p_pk, p_bg = (
                torch.stack(
                    [
                        result.predicted_intensities,
                        result.predicted_sigmas,
                        result.predicted_peak,
                        result.predicted_background,
                    ]
                )
                .detach()
                .cpu()
                .tolist()
            )
            refl = list(zip(p_pos, p_hkl, p_int, p_sig, p_pk, p_bg))
        else:
            refl = [
                (rc, hk, i, s, 0.0, 0.0)
                for rc, hk, keep, i, s in zip(
                    positions, hkl, indexed, intensities, sigmas
                )
                if keep
            ]

        refl = [r for r in refl if math.isfinite(r[3]) and r[3] > 0.0]

        max_recip = max(
            (self._resolution_nm_inv(row, col) for (row, col), *_ in refl),
            default=0.0,
        )
        limit = result.diffraction_limit
        drl_recip = limit if (limit is not None and math.isfinite(limit)) else max_recip

        lines = [
            "--- Begin crystal",
            f"Cell parameters {a_nm:.5f} {b_nm:.5f} {c_nm:.5f} nm, "
            f"{al:.2f} {be:.2f} {ga:.2f} deg",
            "astar = {:+.7f} {:+.7f} {:+.7f} nm^-1".format(*astar),
            "bstar = {:+.7f} {:+.7f} {:+.7f} nm^-1".format(*bstar),
            "cstar = {:+.7f} {:+.7f} {:+.7f} nm^-1".format(*cstar),
            f"lattice_type = {cell.lattice_type or 'triclinic'}",
            f"centering = {cell.centering or 'P'}",
            f"unique_axis = {cell.unique_axis or '?'}",
            f"profile_radius = {_profile_radius_nm_inv(result.rmsd):.5f} nm^-1",
            # orientation-only refinement; detector position is never refined
            "predict_refine/det_shift x = 0.000000 y = 0.000000 mm",
            f"probixi/rmsd = {result.rmsd:.6f} A^-1",
        ]
        if result.scale is not None:
            lines.append(
                f"probixi/scale = {result.scale:.5f} {result.scale_sigma or 0.0:.5f}"
            )
        if result.enrichment is not None:
            lines.append(f"probixi/enrichment = {result.enrichment:.3f}")
        if result.enrich_p is not None:
            lines.append(f"probixi/enrich_p = {result.enrich_p:.3e}")
        lines += [
            f"diffraction_resolution_limit = {_resolution_line(drl_recip)}",
            f"num_reflections = {len(refl)}",
            "num_saturated_reflections = 0",
            "num_implausible_reflections = 0",
            "Reflections measured after indexing",
            "   h    k    l          I   sigma(I)       peak background  "
            "fs/px  ss/px panel",
        ]
        for (
            (row, col),
            (h, k, l),  # noqa: E741
            intensity,
            sigma,
            peak,
            background,
        ) in refl:
            lines.append(
                f"{int(h):4d} {int(k):4d} {int(l):4d} {intensity:10.2f} "
                f"{sigma:10.2f} {peak:10.2f} {background:10.2f} "
                f"{col:6.1f} {row:6.1f} {self._panel_for(col, row)}"
            )
        lines += ["End of reflections", "--- End crystal"]
        return lines


def _resolution_line(recip_nm_inv: float) -> str:
    # CrystFEL '<X> nm^-1 or <Y> A' from 1/d in nm^-1 (d_A = 10 / recip).
    if recip_nm_inv <= 0.0:
        return "0.000000 nm^-1 or inf A"
    d_angstrom = 10.0 / recip_nm_inv
    return f"{recip_nm_inv:.6f} nm^-1 or {d_angstrom:.6f} A"


def _panel_bounds(
    panels: Optional[dict],
) -> list[tuple[str, int, int, int, int]]:
    # Flatten panels to (name, min_fs, max_fs, min_ss, max_ss)
    out: list[tuple[str, int, int, int, int]] = []
    if not panels:
        return out
    for name, data in panels.items():
        try:
            out.append(
                (
                    str(name),
                    int(data["min_fs"]),
                    int(data["max_fs"]),
                    int(data["min_ss"]),
                    int(data["max_ss"]),
                )
            )
        except (KeyError, TypeError, ValueError):
            continue
    return out


def _build_frame_ranges(files: Optional[dict]) -> list[tuple[int, int, str]]:
    # Cumulative (start, stop, filename) ranges over files in load order.
    ranges: list[tuple[int, int, str]] = []
    if not files:
        return ranges
    start = 0
    for fname, info in files.items():
        n = int(getattr(info, "n_frames", 0))
        ranges.append((start, start + n, str(getattr(info, "filename", fname))))
        start += n
    return ranges
